---
- name: host file update - Local DNS setup across all the servers
  hosts: "tomcat-nodes"
  gather_facts: yes
    
  ##plugin: amazon.aws.aws_ec2
  #regions: 
  #  - us-east-1
  #  - us-east-2
      
  tasks:

    - name: List several EC2 instances according to their name tag
      ec2_instance_info:
        region:
          - us-east-1
          - us-east-2
      register: result

    - debug:
        var: result

    - name: Update the /etc/hosts file with node name
      tags: etchostsupdate
      become: yes
      become_user: "root"
      lineinfile:
        path: "/etc/ansible/hosts"
        regexp: ".*\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }}\t{{ hostvars[item]['ansible_hostname']}}\t{{ hostvars[item]['ansible_hostname']}}"
        state: present
        backup: no
      register: etchostsupdate
      when: ansible_hostname != "{{ item }}" or ansible_hostname == "{{ item }}"
      with_items: "{{groups['tomcat-nodes']}}"

    - debug:
        var: etchostsupdate
